### ISSUE TITLE
Skipped mutation after increasing workers

### ISSUE THREAD

**Issue by AndreiBogdanPislaru** [mull-project/mull#887]
Hello, I just noticed that more workers I use more mutation mull skips, I use the flag `--workers`.
It is this normal? I was trying to increase the number of threads to make mull run faster.

**Comment by AlexDenisov** [comment]
This is certainly not normal!
Do you have a reproducer?

**Comment by AndreiBogdanPislaru** [comment]
Nothing small enough to be able to be posted here. The problem involves a class project which all students take part. When I increase the workers Mull not only skips a lot of mutations but also give me different scores every time. I also tried to reproduce it on a small program but all worked well, so I have not many examples I can post. I could record the steps I do and send you the video if it can be helpful, but the only thing I change is the number of workers. 
The tests are based on GoogleTest framework, this could be a problem?

**Comment by AlexDenisov** [comment]
There was a bug that is fixed in version 0.11.1. I would appreciate if you can check whether it resolves at least part of the issue for you @AndreiBogdanPislaru.

**Comment by AndreiBogdanPislaru** [comment]
Hello, thank you very much for the feedback, I made the upgrade but I still have the same problem.

**Comment by AlexDenisov** [comment]
@AndreiBogdanPislaru the recorded steps would be highly appreciated!

**Comment by AndreiBogdanPislaru** [comment]
@AlexDenisov Hello, I apologize for the delay, this is the record:

https://streamable.com/t4ydn6

**Comment by m42e** [comment]
@AndreiBogdanPislaru Is there some external dependency your test rely on? Some file, or inter-process shared object/database?

**Comment by AndreiBogdanPislaru** [comment]
@m42e, Hello thank you for your time, our tests are based on google test.

**Comment by m42e** [comment]
I meant something like are you doing writes to a file or database or alike?

**Comment by AndreiBogdanPislaru** [comment]
The tested program writes some logs, but the tests didn't do.

**Comment by m42e** [comment]
Can you share logs from a run with the -debug switch, once with 1 worker and once with many?

**Comment by AndreiBogdanPislaru** [comment]
Sure, Thank you :D

[debug_one_worker.txt](https://github.com/mull-project/mull/files/7609088/debug_one_worker.txt)
[debug_twenty_workers.txt](https://github.com/mull-project/mull/files/7609089/debug_twenty_workers.txt)

**Comment by m42e** [comment]
It really seems that it does not properly recognize the return value of the test runs. You could try run mull-cxx with the `--keep-executable` flag and launch the executable yourself.

Once with simply the generated binary
```
<the binary created by mull>
```
and once like this:
```
cxx_gt_to_ge:/home/andrei2/APGA_2/APGA/Code/System/CTL_FLC/ctl_flc_private_aux.c:157:44=1 <the binary created by mull>
```

and check the output and the exit codes.

**Comment by AndreiBogdanPislaru** [comment]
So far now, I went in the tmp volder and I tried:

`./mull-<executable serial>.exe`  It runs the test, no problems here

`mull-cxx-12 ./mull-<executable serial>.exe` It gives me a no bitcode: x86_64 warning

`mull-cxx-12 mutators cxx_gt_to_ge:/home/andrei2/APGA_2/APGA/Code/System/CTL_FLC/ctl_flc_private_aux.c:157:44=1 ./mull-<executable serial>.exe` It says no option with this name found

**Comment by m42e** [comment]
Just the generated executables not mull. This should enable exactly one mutation that is found in the version with one worker

**Comment by AndreiBogdanPislaru** [comment]
If i run 

`cxx_gt_to_ge:/home/andrei2/APGA_2/APGA/Code/System/CTL_FLC/ctl_flc_private_aux.c:157:44=1 <the binary created by mull>
`
it tells me "File or directory doesn't exist".

**Comment by m42e** [comment]
ok, then one more try:
```
env cxx_gt_to_ge:/home/andrei2/APGA_2/APGA/Code/System/CTL_FLC/ctl_flc_private_aux.c:157:44=1 <the binary created by mull> 
```

**Comment by m42e** [comment]
Example:

main.cpp
```
#include <iostream>

int call_me(int a, int b, int c){
  if(b > c){
    std::cout << "b>c" << std::endl;
    if (a == 0){
      std::cout << "a == 0" << std::endl;
      return b + c;
    }else{
      std::cout << "a != 0" << std::endl;
      return c-b;
    }
  }
  return a+b;
}

int main(){

  int r = call_me(1,3,2);

  return 0;
}
```

```
clang++ main.cpp -g3 -O0 -fembed-bitcode
```

```
/Users/matthiasbilger/git/mull/build/tools/mull-cxx/mull-cxx-13 -linker-flags='-lstdc++' -debug ./a.out -keep-executable
```
output:
```
[debug] Diagnostics: Debug Mode enabled. Debug-level messages will be printed.
[info] Extracting bitcode from executable (threads: 1)
       [################################] 1/1. Finished in 3ms
[info] Loading bitcode files (threads: 1)
       [################################] 1/1. Finished in 11ms
[info] Sanity check run (threads: 1)
       [################################] 1/1. Finished in 307ms
[info] Gathering functions under test (threads: 1)
       [################################] 1/1. Finished in 0ms
[info] Applying function filter: no debug info (threads: 16)
       [################################] 64/64. Finished in 1ms
[info] Applying function filter: file path (threads: 16)
       [#########################-------] 36/45       [################################] 45/45. Finished in 13ms
[info] Instruction selection (threads: 16)
       [############################----] 40/45       [################################] 45/45. Finished in 11ms
[info] Searching mutants across functions (threads: 16)
       [##########################------] 37/45       [################################] 45/45. Finished in 11ms
[info] Applying filter: no debug info (threads: 16)
       [################################] 30/30. Finished in 1ms
[info] Applying filter: file path (threads: 16)
       [##########################------] 25/30       [################################] 30/30. Finished in 10ms
[info] Applying filter: junk (threads: 16)
/Users/matthiasbilger/git/mull/example/887/main.cpp:1:10: fatal error: 'iostream' file not found
#include <iostream>
         ^~~~~~~~~~
[warning] Cannot parse file: '/Users/matthiasbilger/git/mull/example/887/main.cpp':
mull-cxx /Users/matthiasbilger/git/mull/example/887/main.cpp 
Make sure that the flags provided to Mull are the same flags that are used for normal compilation.
[debug] CXXJunkDetector: mutation "Add to Sub": /Users/matthiasbilger/git/mull/example/887/main.cpp:8:16 (end: 8:17)
[debug] CXXJunkDetector: mutation "Equal to Not Equal": /Users/matthiasbilger/git/mull/example/887/main.cpp:6:11 (end: 6:13)
[debug] CXXJunkDetector: mutation "Greater Than to Less Or Equal": /Users/matthiasbilger/git/mull/example/887/main.cpp:4:8 (end: 4:9)
[debug] CXXJunkDetector: mutation "Add to Sub": /Users/matthiasbilger/git/mull/example/887/main.cpp:14:11 (end: 14:12)
[debug] CXXJunkDetector: mutation "Sub to Add": /Users/matthiasbilger/git/mull/example/887/main.cpp:11:15 (end: 11:16)
[debug] CXXJunkDetector: mutation "Greater Than to Greater or Equal": /Users/matthiasbilger/git/mull/example/887/main.cpp:4:8 (end: 4:9)
       [################################] 30/30. Finished in 32ms
[info] Prepare mutations (threads: 1)
       [################################] 1/1. Finished in 0ms
[info] Cloning functions for mutation (threads: 1)
       [################################] 1/1. Finished in 13ms
[info] Removing original functions (threads: 1)
       [################################] 1/1. Finished in 10ms
[info] Redirect mutated functions (threads: 1)
       [################################] 1/1. Finished in 11ms
[info] Applying mutations (threads: 1)
       [################################] 6/6. Finished in 12ms
[info] Deduplicate mutants (threads: 1)
       [################################] 1/1. Finished in 0ms
[info] Compiling original code (threads: 1)
[debug] Emitted object file: /var/folders/xw/dsms5nqd4xn1y_rpj14qn08m0000gn/T/mull-2c499e.o for bitcode file: /var/folders/xw/dsms5nqd4xn1y_rpj14qn08m0000gn/T/mull-a5fcee.bc
       [################################] 1/1. Finished in 43ms
[info] Link mutated program (threads: 1)
[debug] Link command: clang -lstdc++ /var/folders/xw/dsms5nqd4xn1y_rpj14qn08m0000gn/T/mull-2c499e.o -o /var/folders/xw/dsms5nqd4xn1y_rpj14qn08m0000gn/T/mull-b8bc02.exe
       [################################] 1/1. Finished in 183ms
[info] Mutated executable: /var/folders/xw/dsms5nqd4xn1y_rpj14qn08m0000gn/T/mull-b8bc02.exe
[info] Warm up run (threads: 1)
       [################################] 1/1. Finished in 168ms
[info] Baseline run (threads: 1)
       [################################] 1/1. Finished in 5ms
[info] Running mutants (threads: 6)
[debug] /Users/matthiasbilger/git/mull/example/887/main.cpp:4:82
[debug] /Users/matthiasbilger/git/mull/example/887/main.cpp:4:82
[debug] /Users/matthiasbilger/git/mull/example/887/main.cpp:6:112
[debug] /Users/matthiasbilger/git/mull/example/887/main.cpp:14:112
[debug] /Users/matthiasbilger/git/mull/example/887/main.cpp:11:152
[debug] /Users/matthiasbilger/git/mull/example/887/main.cpp:8:162
       [################################] 6/6. Finished in 11ms
[info] Survived mutants (6/6):
/Users/matthiasbilger/git/mull/example/887/main.cpp:4:8: warning: Survived: Replaced > with >= [cxx_gt_to_ge]
  if(b > c){
       ^
/Users/matthiasbilger/git/mull/example/887/main.cpp:4:8: warning: Survived: Replaced > with <= [cxx_gt_to_le]
  if(b > c){
       ^
/Users/matthiasbilger/git/mull/example/887/main.cpp:6:11: warning: Survived: Replaced == with != [cxx_eq_to_ne]
    if (a == 0){
          ^
/Users/matthiasbilger/git/mull/example/887/main.cpp:8:16: warning: Survived: Replaced + with - [cxx_add_to_sub]
      return b + c;
               ^
/Users/matthiasbilger/git/mull/example/887/main.cpp:11:15: warning: Survived: Replaced - with + [cxx_sub_to_add]
      return c-b;
              ^
/Users/matthiasbilger/git/mull/example/887/main.cpp:14:11: warning: Survived: Replaced + with - [cxx_add_to_sub]
  return a+b;
          ^
[info] Mutation score: 0%
[info] Total execution time: 857ms
```

```
/var/folders/xw/dsms5nqd4xn1y_rpj14qn08m0000gn/T/mull-b8bc02.exe
```
output:
```
b>c
a != 0
```

```
env cxx_gt_to_le:/Users/matthiasbilger/git/mull/example/887/main.cpp:4:8=1 /var/folders/xw/dsms5nqd4xn1y_rpj14qn08m0000gn/T/mull-b8bc02.exe
```
output:
```
```

**Comment by AndreiBogdanPislaru** [comment]
Ok, now it worked, but in both case:

    ./<the binary created by mull>
    
    env cxx_gt_to_ge:/home/andrei2/APGA_2/APGA/Code/System/CTL_FLC/ctl_flc_private_aux.c:157:44=1 ./<the binary created by mull>

I have the same output.
[mull-output.txt](https://github.com/mull-project/mull/files/7610159/mull-output.txt)
[mull-no_env.txt](https://github.com/mull-project/mull/files/7610160/mull-no_env.txt)

I tried also gt_to_le
[mull-gt_to_le.txt](https://github.com/mull-project/mull/files/7610164/mull-gt_to_le.txt)

and in this case I have something different, but nothing closely similar to you. Actually I'm using gtest so i have two main, the first one is the program and the second one is the unit test.

**Comment by m42e** [comment]
Ok, so googletest reports the "failing" as expected. 

Are you using a release version of mull or a self compiled? (I am asking out of curiosity to possible add some more debug output)

And I just thought about using the sqlite reporter, it will capture all the output and exit codes of the mutations.
You may wanna try this and have a look in the resulting sqlite database:

```
.mode column
.headers on
select * from execution_status;
```

**Comment by m42e** [comment]
Ok, I think I found something:
[debug_twenty_worker_executions.txt](https://github.com/mull-project/mull/files/7610237/debug_twenty_worker_executions.txt)
[debug_one_worker_executions.txt](https://github.com/mull-project/mull/files/7610238/debug_one_worker_executions.txt)


The line numbers differ, this means the part with 20 workers is not activating any mutation.

**Comment by AndreiBogdanPislaru** [comment]
One more thing, when `-workers` is setted to 20, not every mull run give me the same mutations:

[first_try.txt](https://github.com/mull-project/mull/files/7610244/first_try.txt)
[second_try.txt](https://github.com/mull-project/mull/files/7610245/second_try.txt)
[third_try.txt](https://github.com/mull-project/mull/files/7610246/third_try.txt)

Actually I'm using the release version.

**Comment by m42e** [comment]
Ok, the last character is not part oft the location, it is the result received from the run.

**Comment by m42e** [comment]
@AndreiBogdanPislaru how long do your test normally run? And how much processors do you actually have in place?

**Comment by AndreiBogdanPislaru** [comment]
If I run just the main test, it ends in 18-22 ms, actually I have 6 physical processors, so 12 logical, I've just tried with 6 and 12 workers, in the first case mull detected at most 2 survived mutations on 52(and sometime no one, the survived mutations should be 6), in the second case only 1, It seems that more the workers are more likely it is that a mutation is skipped.

I also tried to mull a different set of test (this one less tested than the previous one), with 1 worker it give me 36/78 survived mutations, with 6 worker I had the same score 7 times on 10 and 3 times on 10 it skiped one mutation, with 10 workers I had a 25/78, 20/78, 20/78, 15/78 and 22/78 survived mutationsl, with 20 workers mull detected at most 3 mutations, but most of the time gave me a 100% killed mutations.

**Comment by m42e** [comment]
I think you should have a look, if you receive timeouts. If there are also timeouts there, I think there is still something wrong, because the default timeout is 30 seconds.

**Comment by AndreiBogdanPislaru** [comment]
I've also setted timedout at 300'000 already, cause I have other tests lasting a while, but I've just used the ` cat /proc/cpuinfo` comand and popped up my Ubuntu is using just a single core :'(

**Comment by AndreiBogdanPislaru** [comment]
Ok, I setted the virtual machine to run on 12 cores and now I haven't the problem anymore, I 've made the same tests and no more skipped mutations, thank you very much, I'm so happy I finally figured out, it was my bad, I'm sorry I wasted your time.

**Comment by m42e** [comment]
You have not wasted time. I use the tool in production and such a bug would really make it useless :). Glad to have figured out what was the issue.
